# Generated by Django 4.2.7 on 2024-04-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0004_alter_kruzok_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cislo_domu',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='obec',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='psc',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ulica',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
