# Generated by Django 4.2.7 on 2023-12-08 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='createDate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publishDate',
        ),
        migrations.AddField(
            model_name='post',
            name='create_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
